environment   = "production"
bucket_name   = "clcm3102-group1-frontend"
administrator = "z.fu177@mybvc.ca"
service_name  = "dental_office"
public_key    = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKjHqHuJUEXdgFDE4ivQt3ZA5bHYFfkIcdMlMqYIu8HM z.fu177@mybvc.ca"
